export const LOGIN = 'LOGIN';
export const LOGIN_PERSIST = 'LOGIN_PERSIST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SEARCH_BEGIN = 'SEARCH_BEGIN';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
export const SEARCH_FAILED = 'SEARCH_FAILED';

export const FETCH_PROPERTY = 'FETCH_PROPERTY';
export const FETCH_PROPERTY_SUCCESS = 'FETCH_PROPERTY_SUCCESS';
export const FETCH_PROPERTY_FAILED = 'FETCH_PROPERTY_FAILED';
